# Generated by Django 3.2.8 on 2021-10-16 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player_white', models.CharField(default='', max_length=50)),
                ('player_black', models.CharField(default='', max_length=50)),
                ('history', models.TextField()),
                ('current_position', models.TextField()),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
