# Generated by Django 3.2.7 on 2021-10-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='color_turn',
            field=models.CharField(default='white', max_length=5),
        ),
        migrations.AddField(
            model_name='game',
            name='is_finished',
            field=models.BooleanField(null=True),
        ),
    ]
